### ISSUE TITLE
Upgrade `RA-Soul` to the Latest `soul` Version

### ISSUE THREAD

**Issue by ebenezer-melkamu** [DeepBlueCLtd/RA-Soul#16]
#### May 27, 2024

# Upgrade `RA-Soul` to the Latest `soul` Version

# 1. Goal

* The **`RA-Soul`** project is currently using an outdated version of Soul. We need to upgrade to the latest version and implement the authentication setup.

# 2. Review Existing Data Providers

## 2.1. Express-Mongose-Ra-Json-Server Provider

* **RA Provider Link**

  ```
  https://github.com/NathanAdhitya/express-mongoose-ra-json-server/blob/master/src/index.ts
  ```

* **Data Provider Methods**

  ```
  => getOne
  => getMany
  => create
  => update
  => delete
  ```

* **Auth Provider Methods**

  ```
  None
  ```

* **Database**

  ```
  MongoDb
  ```

* **Unit Test**

  ```
  None
  ```

  

## 2.2. Express-Sequelize-Crud Provider

* **RA Provider Link**

  ```
  https://github.com/nicgirault/express-crud-router
  ```

* **Data Provider Methods**

  ```
  => getOne
  => getList
  => create
  => update
  => delete
  ```

* **Auth Provider Methods**

  ```
  None
  ```

* **Database**

  ```
  SQLite
  ```

* **Unit Test**

  ```
  Yes
  ```

  

## 2.3. Ra-Data-Feathers Provider

* **RA Provider Link**

  ```
  https://github.com/josx/ra-data-feathers
  ```

* **Data Provider Methods**

  ```
  => getList
  => getOne
  => getMany
  => getManyReference
  => create
  => update
  => updateMany
  => delete
  => deleteMany
  ```

* **Auth Provider Methods**

  ```
  => authLogin
  => authLogout
  => authCheck
  => authError
  => authGetPermissions
  ```

* **Database**

  ```
  Not Sure
  ```

* **Unit Test**

  ```
  Yes
  ```

  

## 2.4. Ra-Data-Postgrest

* **RA Provider Link**

  ```
  https://github.com/raphiniert-com/ra-data-postgrest
  ```

* **Data Provider Methods**

  ```
  => getList
  => getOne
  => getMany
  => getManyReference
  => create
  => update
  => updateMany
  => delete
  => deleteMany
  ```

* **Auth Provider Methods**

  ```
  None
  ```

* **Database**

  ```
  PostgreSQL
  ```

* **Unit Test**

  ```
  Yes
  ```

## 2.5. Ra-Data-Dexie

* **RA Provider Link**

  ```
  https://github.com/tykoth/ra-data-dexie
  ```

* **Data Provider Methods**

  ```
  => getList
  => getOne
  => getMany
  => getManyReference
  => create
  => update
  => delete
  ```

* **Auth Provider Methods**

  ```
  None
  ```

* **Database**

  ```
  IndexDB
  ```

* **Unit Test**

  ```
  None
  ```

**Comment by IanMayo** [comment]
Task now complete.
