### ISSUE TITLE
Deploy soul4reactadmin data provider

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RA-Soul#2]
Run our new data provider on the chinook.db backend database

Hmm @AbegaM  - I'm not quite convinced this is the next step.  I _think_ we should serve the real database for my app.  I hope to have a new SQLite version tomorrow.

**Comment by ebenezer-melkamu** [comment]
@IanMayo - Should I wait until you get the new database?

**Comment by IanMayo** [comment]
> @IanMayo - Should I wait until you get the new database?

please.  Let's talk again tomorrow morning, and see where we are.
