### ISSUE TITLE
Get Soul to serve our SQLite database

### ISSUE THREAD

**Issue by IanMayo** [DeepBlueCLtd/RA-Soul#3]
Obtain copy of empty SQLite database.

Get `Soul` to serve the database, from Heroku.

(hopefully) resolve CORS issues so my devs can connect to the Heroku instance, and configure the `react-admin` data provider to connect to Heroku

**Comment by ebenezer-melkamu** [comment]
@IanMayo, This is the second task i have to work on right?

**Comment by IanMayo** [comment]
yes please @AbegaM
